### PR TITLE
Add SEO meta tags with an example of how to define keywords in the example post.

### PR DESCRIPTION
**Pull request by treacher**
What do you think of this? I added it myself and thought it might be something bloggers would be interested in when using this.

### CODE REVIEW

**Comment by nickbalestra** [comment]
@rcmachado awesome job with those pr on your fork, i've been a bit away from this, what you think about joining forces in maintaining this?

**Comment by rcmachado** [comment]
@nickbalestra thanks nick :) Yes, sure. How do you think that I can help?

**Comment by nickbalestra** [comment]
@rcmachado I can grant you writing privileges on this repo so that we get it to parity and merge what need to be merged in the upcoming days and then maintain it together. Let me know if you have a different idea/plan to suggest

**Comment by rcmachado** [comment]
@nickbalestra Ok, no problem :)

**Pull request closed without merging**
